In [1]:
import pandas as pd

In [2]:
earthquake_dataset = pd.read_csv("earthquake_dataset.csv")
earthquake_dataset

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2024-01-18T02:18:19.690Z,38.807835,-122.823334,2.03,1.49,md,21.0,54.0,0.004681,0.02,...,2024-01-18T02:19:54.732Z,"Geysers, CA",earthquake,0.22,0.310,0.150,22.0,automatic,nc,nc
1,2024-01-18T02:16:52.710Z,38.808498,-122.823669,2.01,1.33,md,23.0,53.0,0.004320,0.02,...,2024-01-18T02:28:11.196Z,"Geysers, CA",earthquake,0.19,0.340,0.140,23.0,automatic,nc,nc
2,2024-01-18T01:55:45.006Z,64.994500,-147.409700,5.20,1.50,ml,NaN,NaN,NaN,0.60,...,2024-01-18T02:03:52.136Z,"Fox, Alaska",earthquake,NaN,0.300,NaN,NaN,automatic,ak,ak
3,2024-01-18T01:48:21.130Z,36.020333,-117.781167,1.55,1.39,ml,27.0,62.0,0.013780,0.16,...,2024-01-18T01:54:25.834Z,"Little Lake, CA",earthquake,0.17,0.160,0.139,11.0,automatic,ci,ci
4,2024-01-18T01:46:32.440Z,38.826668,-122.853836,2.44,0.28,md,10.0,99.0,0.002529,0.01,...,2024-01-18T02:04:12.038Z,"Geysers, CA",earthquake,0.40,1.070,0.160,11.0,automatic,nc,nc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8881,2023-12-19T02:43:10.876Z,-7.242500,119.138700,593.76,4.90,mb,95.0,26.0,2.074000,0.75,...,2024-01-16T01:30:21.040Z,"Bima, Indonesia",earthquake,3.86,6.268,0.054,107.0,reviewed,us,us
8882,2023-12-19T02:42:29.472Z,-22.785000,172.366200,10.00,5.30,mww,64.0,74.0,4.546000,0.74,...,2024-01-15T23:45:16.040Z,southeast of the Loyalty Islands,earthquake,10.15,1.808,0.075,17.0,reviewed,us,us
8883,2023-12-19T02:39:21.180Z,33.111333,-115.624833,9.51,1.34,ml,32.0,93.0,0.066410,0.19,...,2023-12-19T15:49:01.616Z,"Westmorland, CA",earthquake,0.21,0.520,0.214,20.0,reviewed,ci,ci
8884,2023-12-19T02:35:17.230Z,38.826332,-122.804833,3.06,0.64,md,8.0,147.0,0.005036,0.01,...,2023-12-19T04:50:10.666Z,"Geysers, CA",earthquake,1.08,1.470,0.120,7.0,automatic,nc,nc
8885,2023-12-19T02:34:46.768Z,57.893500,-153.765300,56.30,1.50,ml,NaN,NaN,NaN,0.32,...,2024-01-05T18:45:34.407Z,"Larsen Bay, Alaska",earthquake,NaN,0.500,NaN,NaN,reviewed,ak,ak

In [3]:
earthquake_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8886 entries, 0 to 8885
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             8886 non-null   object
 1   latitude         8886 non-null   float64
 2   longitude        8886 non-null   float64
 3   depth            8886 non-null   float64
 4   mag              8886 non-null   float64
 5   magType          8886 non-null   object
 6   nst              7092 non-null   float64
 7   gap              7092 non-null   float64
 8   dmin             5965 non-null   float64
 9   rms              8886 non-null   float64
 10  net              8886 non-null   object
 11  id               8886 non-null   object
 12  updated          8886 non-null   object
 13  place            8886 non-null   object
 14  type             8886 non-null   object
 15  horizontalError  6349 non-null   float64
 16  depthError       8886 non-null   float64
 17  magError         7076 non-null   float64
 18  magNst           7090 non-null   float64
 19  status           8886 non-null   object
 20  locationSource   8886 non-null   object
 21  magSource        8886 non-null   object
dtypes: float64(12), object(10)
memory usage: 1.5+ MB

In [4]:
earthquake_dataset.isnull().sum()

time                  0
latitude              0
longitude             0
depth                 0
mag                   0
magType               0
nst                1794
gap                1794
dmin               2921
rms                   0
net                   0
id                    0
updated               0
place                 0
type                  0
horizontalError    2537
depthError            0
magError           1810
magNst             1796
status                0
locationSource        0
magSource             0
dtype: int64

In [5]:
earthquake_dataset.head(5)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2024-01-18T02:18:19.690Z,38.807835,-122.823334,2.03,1.49,md,21.0,54.0,0.004681,0.02,...,2024-01-18T02:19:54.732Z,"Geysers, CA",earthquake,0.22,0.31,0.150,22.0,automatic,nc,nc
1,2024-01-18T02:16:52.710Z,38.808498,-122.823669,2.01,1.33,md,23.0,53.0,0.004320,0.02,...,2024-01-18T02:28:11.196Z,"Geysers, CA",earthquake,0.19,0.34,0.140,23.0,automatic,nc,nc
2,2024-01-18T01:55:45.006Z,64.994500,-147.409700,5.20,1.50,ml,NaN,NaN,NaN,0.60,...,2024-01-18T02:03:52.136Z,"Fox, Alaska",earthquake,NaN,0.30,NaN,NaN,automatic,ak,ak
3,2024-01-18T01:48:21.130Z,36.020333,-117.781167,1.55,1.39,ml,27.0,62.0,0.013780,0.16,...,2024-01-18T01:54:25.834Z,"Little Lake, CA",earthquake,0.17,0.16,0.139,11.0,automatic,ci,ci
4,2024-01-18T01:46:32.440Z,38.826668,-122.853836,2.44,0.28,md,10.0,99.0,0.002529,0.01,...,2024-01-18T02:04:12.038Z,"Geysers, CA",earthquake,0.40,1.07,0.160,11.0,automatic,nc,nc

In [6]:
earthquake_dataset.describe()

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,8886.000000,8886.000000,8886.000000,8886.000000,7092.000000,7092.000000,5965.000000,8886.000000,6349.000000,8886.000000,7076.000000,7090.000000
mean,39.308700,-111.205884,22.779244,1.636482,24.467851,109.605255,0.553678,0.276822,1.638979,2.037707,0.247804,16.977292
std,18.276848,68.838488,51.627071,1.223509,23.427687,63.652406,2.196805,0.273490,2.914440,6.507358,0.390754,29.095417
min,-65.494800,-179.957700,-3.160000,-1.270000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,33.408500,-150.502125,3.000000,0.830000,10.000000,64.000000,0.012000,0.090000,0.250000,0.440000,0.110000,6.000000
50%,38.816250,-122.264500,7.738300,1.420000,18.000000,91.000000,0.053830,0.170000,0.450000,0.750000,0.173000,11.000000
75%,53.236350,-114.302992,16.490000,2.050000,32.000000,140.000000,0.139100,0.420000,1.000000,1.500000,0.244314,19.000000
max,80.512900,179.884600,660.826000,7.500000,598.000000,344.000000,43.556000,3.250000,17.780000,449.100000,5.180000,722.000000

In [7]:
earthquake_dataset.memory_usage()

Index                128
time               71088
latitude           71088
longitude          71088
depth              71088
mag                71088
magType            71088
nst                71088
gap                71088
dmin               71088
rms                71088
net                71088
id                 71088
updated            71088
place              71088
type               71088
horizontalError    71088
depthError         71088
magError           71088
magNst             71088
status             71088
locationSource     71088
magSource          71088
dtype: int64